# Generated by Django 2.2.1 on 2019-06-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pasportyst',
        ),
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.CharField(default='-', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookNumber',
        ),
    ]
