# Generated by Django 2.2.1 on 2019-06-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_person_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='registered_date',
            new_name='registered',
        ),
        migrations.RemoveField(
            model_name='person',
            name='number_in_book',
        ),
        migrations.AddField(
            model_name='person',
            name='continued',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='continued_period',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='old_address',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='registered_period',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
