# Generated by Django 2.2.1 on 2019-06-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190613_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='de_registered_date',
            new_name='de_registered',
        ),
    ]
